# Generated by Django 4.2.1 on 2023-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Opportunity',
            new_name='Fırsat',
        ),
    ]
