# Generated by Django 4.2.1 on 2023-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_person_rename_opportunity_fırsat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fırsat',
            old_name='Musteri',
            new_name='musteri',
        ),
        migrations.AlterField(
            model_name='fırsat',
            name='anlasma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fırsat',
            name='asama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fırsat',
            name='durum',
            field=models.CharField(max_length=100),
        ),
    ]
